### ISSUE TITLE
MVKaran \ Exotel \ ExotelException Unauthorized;

### ISSUE THREAD

**Issue by gopakumar180** [mvkaran/exotel-php#1]
When I use this  code 

        $client = new Client($sid, $token);
         $result = $client->send_sms([
             'from' => 'xxx', //One of your Exophones,
             'to' => 'xx', 
             'body' => 'Hey there! Explore Exotel!', 
        
            'priority' => 'normal', //Optional. Can be ignored from the array itself
             'status_callback' => '', //Optional. Can be ignored from the array itself
         ]);
Getting error as  "MVKaran \ Exotel \ ExotelException Unauthorized;".

Please help me.

**Comment by mvkaran** [comment]
Hi @gopakumar180 I am not actively maintaining this since the API versions seem to have changed significantly. I would suggest that you check out the sample code from here - https://github.com/exotel/ExotelAPI/tree/master/php
